name: CraftGUI
version: '${project.version}'
main: net.azisaba.life.CraftGUI
api-version: '1.15'
authors: [albardoo02]
description: 新しいCraftGUIプラグイン
commands:
  rgui:
    aliases:
      - ragui
      - compress
      - compressgui
      - assyuku
      - assyukugui
      - craftgui